[package]
name = "axum-connect"
version = "0.1.5"
authors = ["Alec Thilenius <alec@thilenius.com>"]
edition = "2021"
categories = [
  "network-programming",
  "web-programming",
  "web-programming::http-server",
]
description = "Connect-Web RPC for Axum"
keywords = ["rpc", "axum", "protobuf", "connect"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/AThilenius/axum-connect"

[dependencies]
async-trait = "0.1.64"
axum = "0.6.9"
futures = "0.3.26"
pbjson = "0.5.1"
prost = "0.11.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
