[package]
name = "axum-connect-build"
version = "0.1.0"
edition = "2021"
categories = ["rpc", "connect-web", "axum", "http"]
description = "Connect-Web RPC for Axum"
keywords = ["rpc", "axum", "protobuf", "connect"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/AThilenius/axum-connect"

[dependencies]
anyhow = "1.0"
convert_case = "0.6.0"
protobuf = { git = "https://github.com/AThilenius/rust-protobuf.git" }
protobuf-codegen = { git = "https://github.com/AThilenius/rust-protobuf.git" }
protobuf-parse = { git = "https://github.com/AThilenius/rust-protobuf.git" }
