[package]
name = "axum-connect-example"
version = "0.2.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
axum = "0.6.9"
axum-connect = { path = "../axum-connect" }
prost = "0.12.1"
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
axum-connect-build = { path = "../axum-connect-build" }
