[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.9"
axum-connect = { path = "../axum-connect" }
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
axum-connect-build = { path = "../axum-connect-build" }
